server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: merchant-catalog-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
    git:
      mode: simple

info:
  app:
    name: ${spring.application.name}
