#!/bin/sh
set -eu

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
CREATE DATABASE IF NOT EXISTS aituan_identity CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS aituan_merchant CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS aituan_trade CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS aituan_platform CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS '${IDENTITY_DB_USERNAME}'@'%' IDENTIFIED BY '${IDENTITY_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${MERCHANT_DB_USERNAME}'@'%' IDENTIFIED BY '${MERCHANT_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${TRADE_DB_USERNAME}'@'%' IDENTIFIED BY '${TRADE_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${PLATFORM_DB_USERNAME}'@'%' IDENTIFIED BY '${PLATFORM_DB_PASSWORD}';

GRANT ALL PRIVILEGES ON aituan_identity.* TO '${IDENTITY_DB_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON aituan_merchant.* TO '${MERCHANT_DB_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON aituan_trade.* TO '${TRADE_DB_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON aituan_platform.* TO '${PLATFORM_DB_USERNAME}'@'%';
FLUSH PRIVILEGES;
EOSQL
